### ISSUE TITLE
Encoding error on macOS

### ISSUE THREAD

**Issue by 8bitgentleman** [karlicoss/HPI#66]
I am getting an error similar to the error discussed in karlicoss/rexport#5 . I just cloned this repo on macOS 10.14.6 using python 3.7 in a virtual env. I am trying to access the reddit exports using the simple example shown at the top of the [HPI README](https://github.com/karlicoss/HPI/blob/master/README.org). 

```
Traceback (most recent call last):
  File "/Users/mtvogel/Documents/PythonScripts/HPI/main.py", line 11, in <module>
    for s in my.reddit.saved():
  File "/Users/mtvogel/Documents/PythonScripts/HPI/env/lib/python3.7/site-packages/cachew/__init__.py", line 764, in wrapper
    for chunk in ichunks(datas, n=chunk_by):
  File "/Users/mtvogel/Documents/PythonScripts/HPI/env/lib/python3.7/site-packages/cachew/__init__.py", line 55, in ichunks
    chunk: List[T] = list(islice(it, 0, n))
  File "/Users/mtvogel/Library/Application Support/my/my/config/repos/rexport/dal.py", line 157, in saved
    for s in self._accumulate(what='saved'):
  File "/Users/mtvogel/Library/Application Support/my/my/config/repos/rexport/dal.py", line 139, in _accumulate
    for f, r in self.raw():
  File "/Users/mtvogel/Library/Application Support/my/my/config/repos/rexport/dal.py", line 133, in raw
    yield f, json.load(fo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/mtvogel/Documents/PythonScripts/HPI/env/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```

**Comment by karlicoss** [comment]
@8bitgentleman thanks for checking, I transferred it! I'll think why it could happen..

**Comment by karlicoss** [comment]
I'll close it since it's stale and there've been so many various fixes since that possible that the issue resolved itself. 
But feel free to reopen if it's still the case!
